# PyTorch Tutorial
Dieses Tutorial ist von mir selbst erstellt. Der Fokus liegt hier nicht auf "auswendig-Lernen" oder einfach nur dem Wissen sämtlicher Details von PyTorch-Funktionalitäten, sondern soll ein funktionales Verständnis ermöglichen, d.h. gewisse Dinge werden evtl. erst selbst implementiert (oder schrittweise hergeleitet), bevor sie hier gezeigt werden. Dieses Tutorial umfasst auch mathematische Formeln, und vieles Weiteres. Es soll die wichtigsten Funktionalitäten von PyTorch zeigen. (und diese Funktionalität auch von anderen Frameworks abgrenzen!!!) PyTorch wird immer wieder angepasst, erweitert und ist keine statische Bibliothek!! (ich versuche framework-agnostisch daran zu gehen, das fällt mir aber sehr schwer, da ich ja nocg gar keine anderen frameworks kenne!!)

> PyTorch (kurz: Torch) ist eine 2016 erschienene Programmbibliothek, basierend auf der in Lua geschriebenen Bibliothek Torch.

Wichtige Zusatzbibliotheken für PyTorch (bes. im Bereich Maschinelles Lernen) sind:
* **Bilderkennung**: `torchvision` (images)
* *Texterkennung*: `torchtext` 
* *Sprach-/Audioerkennung*: `torchaudio`

Eine grundlegende Referenz ist unter anderem:  
- [Offizielle PyTorch-Website](https://docs.pytorch.org/tutorials/beginner/pytorch_with_examples.html)

---


### Voraussetzungen und Einrichtung der Arbeitsumgebung

Ein kurzer Hinweis vorab: Für produktives Arbeiten mit PyTorch benötigt es eine korrekt eingerichtete Ausführungsumgebung sowie grundlegende Vertrautheit mit Python. Kenntnisse in **NumPy** sind hilfreich, aber nicht notwendig.

### Benötigte Komponenten
Zur Einrichtung der Ausführungsumgebung ist es wichtig, folgende Software zu installieren:
- **Python** (ich nutze: *Python 3.9.25*)
- **pip** (ich nutze *pip 24.0*)
- um **Jupyter Notebooks** zu nutzen gibt es mehrere Möglichkeiten, u.a.
    - in VSC: Extensions für Jupyter Notebooks installieren, ipykernel package im virtual environment für Python installieren
- Letztlich muss NumPy über einen beliebigen package manager (z.B. pip) in das virtual environment installiert werden, in dem man arbeitet. (am besten eine Version im PyPI-Index) (ich nutze torch, version *2.0.0*)

Alles andere ist nicht notwendig, um dieses Tutorial zu verstehen. (z.B. Python Linter, Debugging Tools), usw.

(evtl. diesen Aspekt erweitern??)

---

Die Englische Variante findet sich hier: ...

In [110]:
# Beginnen wir damit, PyTorch erstmal zu importieren.

import torch
torch.__version__

'2.0.0+cu117'

> Kurzer Disclaimer: In diesem Tutorial werden wir noch nicht so weit in andere packages vordringen, und eher bei `torch` bleiben, d.h.
* Tensor-Klasse, inklusive einiger fundamentaler Klassen bzw. Datentypen von PyTorch
* Attribute von Tensoren
* verschiedene Funktionem, um Tensoren verschiedener Art zu erstellen
* Operationen auf Tensoren (Methoden)
* Verschiedenes

# Was sind Tensoren?
Ein wesentlicher "Typ" von mathematischen Objekten, mit denen sich PyTorch befasst, sind Tensoren.
Mathematisch gesehen sind Tensoren die Verallgemeinerung von bereits bekannten Konzepten hin zu einem mathematischen Objekt mit beliebig vielen **räumlichen/strukturellen Dimensionen**.
Im Bereich von Data Science, des Maschinellen Lernens und neuronalen Netzen sind Tensoren ein wesentlicher Bestandteil. Sie wurden als mathematisches Objekt quasi "wiederentdeckt", um Berechnungen aus der linearen Algebra und Vektoralgebra in höherdimensionalen Räumen zu ermöglichen. (evtl. bessere Motivation??)

Betrachten wir zunächst einen einfachen Skalar $$a \in \mathbb{R}$$ 
Man könnte auch schreiben $$a \in \mathbb{R}^{1x1}$$ 
Anders ausgedrückt: Ein Skalar kann auch als Vektor mit nur einem Element verstanden werden. Ein Zeilen- oder Spaltenvektor, der nur ein Element enthält, ist de facto der gleiche Vektor. 

Sei der Vektor $$u \in \mathbb{R}^n$$ Man könnte auch schreiben: $v \in \mathbb{R}^{nx1}$ oder $w \in \mathbb{R}^{1xn}$, je nachdem, ob es sich um einen Zeilen- odre Spaltenvektor handelt. Sofern gilt, dass $n=1$, gilt $v=w$. Darüber hinaus bleibt die Frage offen, ob nun gilt, dass $v=u$? (Das ist ein anderes Thema und soll in Morphismen einführen.)

Der springende Punkt ist: Skalaren lassen sich als Sonderfall von Vektoren auffassen, wenn diese nur ein Element enthalten. Vektoren können je nach Anwendungsgebiet unterschiedlich definiert sein. (Dies hat schon vielen Mathematikern vor den Kopf gestoßen, oder Informatikern, die es etwas genauer nehmen wollen.) Der wesentliche Unterschied liegt darin, ob gilt, dass $v=u$, oder nicht.
> Hier eine kurze Aufgabe: Was für Konsequenzen hat das, wenn das gilt bzw. wenn das nicht gilt?

Und jetzt gehen wir nochmals weiter: Vektoren lassen sich auch als Spezialfälle von Matrizen ansehen. Somit auch Skalare. Jede Matrix, die in jeweils einer räumlichen Dimension nur ein "Element" enthält, beschreibt einen Vektor. Sei $A = (a_{ij})_{i=1,...m; j=1,...n}$ Sofern gilt, dass $m=1 \vee n=1$, beschreibt die Matrix einen Vektor mit $m$ bzw. $n$ Elementen.

Es lässt sich feststellen, dass Skalare $0$ räumliche Dimensionen haben ($a \in \mathbb{R}^{nx0x0x0x0x0x0x...}$), Vektoren (klassischerweise) $1$ räumliche Dimension, und Matrizen $2$. Verallgemeinert man dies auf mathematische Strukturen mit beliebig vielen räumlichen/strukturellen Dimensionen $k$, beschreibt man das, was man einen Tensor nennt. (Das Hat Woldemar Voigt 1898 auch bereits erkannt, [[1](https://books.google.de/books?id=JpenEAAAQBAJ)])
* Skalare = Tensoren vom Typ $(0,0)$, Tensor 0. Stufe
* "Spaltenvektoren" = Tensoren vom Typ $(1,0)$, Tensor 1. Stufe
* "Zeilenvektoren" = Tensoren vom Typ $(0,1)$, Tensor 1. Stufe
* Matrizen = Tensoren 2. Stufe
* ??


Ja, so wirklich verstanden, WAS ein Tensor nun ist, habe ich immer noch nicht.


- Indexnotation
- Beziehung zu abelschen Gruppen
- Tensorprodukte????
- kovariant, kontravariant bzgl. einer Stufe
- tensoralgebra
- tensor = multilineare Abbildung
- Tensor = Array beliebiger Ordnung; multilineare Abbildung (und kann auch als Element eines Vektorraums interpretiert werden!!)

PyTorch führt eine neue Klasse bzw. Datentyp ein, nämlich `torch.Tensor`.
Auf diese Art & Weise, lassen sich Tensoren deklarieren, initialisieren, deren Attribute verändern und lesen, und gewisse Methoden der Tensoren nutzen. (Ich glaube nicht, dass das wirklich Tensoren sind.)

Es gibt mehrere Möglichkeiten, Tensoren zu erstellen. Man könnte einfach den Konstruktor `torch.Tensor(data: Any)` nutzen, um damit Tensoren zu erstellen.
Es empfiehlt sich allerdings die Funktion `torch.tensor(data: Any)` zu verwenden.

In [111]:
# Wir können erstmal damit anfangen, Tensoren in PyTorch zu deklarieren und zu initialisieren.
# Dazu nutzen wir Python-Sequenzen oder Listen
# Es existiert die Klasse Tensor. Wir könnten einfach den Konstruktor aufrufen.; es existeir aber auch die Funktion tensor() (für leaf-Tensoren!)
# Was macht den Unterschied??

scalar = torch.tensor(7)
print(scalar)
vector = torch.tensor([1,2,3])
print(vector)
matrix = torch.tensor([[1., -1.], [1., -1.]]) #2x2-Matrix; erst die Zeilen, dann die Spalten!!!!!!!!!!!!!
print(matrix)
fourDimensionalTensor = torch.tensor(
    [
        [
            [1,0], [0,1]
        ], 
        [
            [0,1], [1,0]
        ]
    ]
)
print(fourDimensionalTensor)

T = torch.Tensor([1,2,3,4,5,5,6,7,8,9])
print(T)

# Aufgabe: höherdimensionale Tensoren durchdenken!!!
# was genau sind leaf-Tensoren?
# Wie ist die Reihenfolge der Matrix-Elemente??

tensor(7)
tensor([1, 2, 3])
tensor([[ 1., -1.],
        [ 1., -1.]])
tensor([[[1, 0],
         [0, 1]],

        [[0, 1],
         [1, 0]]])
tensor([1., 2., 3., 4., 5., 5., 6., 7., 8., 9.])


Wie man sieht macht es sich PyTorch recht einfach. Tensoren sind einfach nur geschachtelte bzw. mehrdimensionale Arrays.
Um im Folgenden uns nicht unnötig zu verwirren, sollen Tensoren im folgenden als Spezialfall von Tensoren aufgefasst werden, nämlich Tensoren 1. Stufe bzw mit `shape == torch.Size([n])`. Ignorieren wir einfach mal die Vektoralgebra ein wenig.
Vektoren sind also Elemente aus $\mathbb{R}^{n \times 1}$ bzw. $\mathbb{R}^{1 \times n}$, wobei in manchen Kontexten die Isomorphie zu $\mathbb{R}^{n}$ genutzt wird.
Im Abschnitt "Operationen auf Tensoren" werden wir sehen, wieso es sinnvoller ist, Vektorräume zu ignorieren und stattdessen die Matrizenrechnung als Grundlage zu verwenden.

## Eigenschaften von Tensoren
Wichtigste Attribute von `torch.Tensor` sind:
* `ndim`: strukturelle Dimensionen eines Tensors (`int`), Ordnung/Rang
* `shape`: Angabe eines Arrays, dessen Länge der Ordnung des Tensors entspricht mit jew. der Dimension bzw. Länge der einzelnen Achsen (kann man sich auch mit der Methode `Tensor.size()` ausgeben lassen)
* `requires_grad`: Angabe, ob die Gradienten für diesen Tensor berechnet werden sollen oder nicht (`bool`) (wird später benötigt!!) (Standard ist `False`)

Attribute mit torch-eigenen Datentypen, die jeder `torch.Tensor` hat sind u.a.:
* `dtype`: Objekt, das den Datentyp der Daten eines Tensors beschreibt, u.a. `None`, `torch.float16`/`torch.half`, `torch.float32`/`torch.float`, `torch.float64`/`torch.double`, `torch.int32`, `torch.int64`, `torch.bool`, (es gibt noch viel mehr!) (`torch.dtype`) (Standard ist float32) (ist unveränderbar)
* `device`: Objekt, das das Gerät repräsentiert, auf dem der Tensor zugewiesen ist (d.h. `None`, "cpu, "cuda", usw.) (`torch.device`) (Standard ist "cpu") (ist unveränderbar)
* `layout`: Objekt, das die Speicheranordnung eines Tensors repräsentiert (`torch.layout`) (Standard ist "strided")
...

Hier wird auch direkt klar, dass `PyTorch` ebenfalls die Klasse `torch.Size` nutzt (Unterklasse von `tuple`), um die "Form" von Tensoren zu beschreiben. Das Array beschreibt die Achsenlängen jeweils von der "äußersten" zur "innersten" Dimension. (d.h. `torch.Size([k_i, ..., k_2, k_1])`)

(Diese Attribute sind recht nützlich, um sich die Tensoren besser vorzustellen, mit denen man agiert.)
(Man sollte regelmäßig shape, dtype und device ÜBERPRÜFEN!)

In [112]:
print(scalar.ndim)
print(vector.ndim)
print(matrix.ndim)

0
1
2


In [121]:
for tensor in [scalar, vector, matrix]:
    print(tensor.shape)

s = T.size()
print(s)
print(len(s))
print(s.numel()) #torch.Size.numel()

#Was macht den Unterschied aus??; Ausgabe scheint die gleiche zu sein??

#erstellen von Tensoren, wo man nur die Größe änder, d.h.
#t = T.size(2,3)
#t

torch.Size([])
torch.Size([3])
torch.Size([2, 2])
torch.Size([10])
1
10


In [ ]:
for tensor in [scalar, vector, matrix]:
    print(tensor.dtype)
print(10 * "-")

#Standard-dtypes
x_int = torch.tensor([1,2,3])
x_float = torch.tensor([[4.3, 5.23], [4.6, 9.2]])
x_bool = torch.tensor([[True, False], [True, False]])

print(x_int.dtype)
print(x_float.dtype)
print(x_bool.dtype)

#Man kann den dtype i.d.R. angeben bei der Erstellung von Tensoren, z.B.
tensor1 = torch.tensor([1,2,3], dtype=torch.int32)
tensor2 = torch.tensor([1,2,3], dtype=torch.float64)
tensor3 = torch.tensor([1., 2., 3.], dtype=torch.int64) #-> wirft DeprecationWarning!
print(10 * "-")
for tensor in [tensor1, tensor2, tensor3]:
    print(tensor)
    print(tensor.dtype)
#für nicht Standard-Datentypen wird dieser angezeigt!!

tensor4 = torch.tensor([1,2,3], dtype=torch.int32)
print(tensor4.type()) #gibt tw. Alternativnamen aus; Warum?????????????????

#Casting lassen wir mal außen vor; tensor.type() ???

#Sollte man überhaupt so auf die Attribute von torch.Tensor zugreifen?, Wieso gibt es tensor.size()? als Methode, aber nicht sowas für die anderen Attribute??

torch.int64
torch.int64
torch.float32
----------
torch.int64
torch.float32
torch.bool
----------
tensor([1, 2, 3], dtype=torch.int32)
torch.int32
tensor([1., 2., 3.], dtype=torch.float64)
torch.float64
tensor([1, 2, 3])
torch.int64
torch.IntTensor


/tmp/ipykernel_312180/1343848177.py:17: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  tensor3 = torch.tensor([1., 2., 3.], dtype=torch.int64) #-> wirft DeprecationWarning!


In [ ]:
# Es gibt verschiedene Arten von Gerätetypen. Die typischten sind: "cpu", "cuda" (oder auch "mps", "xpu", "xla", "meta")
# Es gibt auch sowas wie Geräteordnungszahlen (device ordinals) und accelerators!

for tensor in [scalar, vector, matrix]:
    print(tensor.device) # Standard ist "cpu"

tensor4 = torch.tensor([42, 42, 42], dtype=torch.float64, device="cuda") # implicit index is the "current device index"
print(tensor4.device)

print(torch.device("cuda", 1))

#Geräte (devices) können sogar als Kontextmanager!! verwendet werden, d.h.

with torch.device(0):
    t = torch.tensor([1,2,3])
print(t.device)

# ja, das habe ich noch nicht so ganz verstanden!!

# es gibt auch das Modul `torch.cuda`

#man kann wohl auch tensoren erstellen, in dem man einfach nur dsa Gerät ändert, d.h. T = S.to(device)

cpu
cpu
cpu
cuda:0
cuda:1
cuda:0


In [8]:
for tensor in [scalar, vector, matrix]:
    print(tensor.layout) # Standard ist torch.strided (dichte Tensoren, s. "strided arrays")

torch.strided
torch.strided
torch.strided


### Einschub: Gradientenberechnung
Das Attribut `torch.Tensor.requires_grad` kann auf `True` gesetzt werden, um ...


Der Datentyp `torch.no_grad` und `torch.enable_grad` bzw. die Klasse kann auch als Kontextmanager verwendet werden

In [90]:
tensorGrad = torch.tensor([3, 7, 2 ,3], dtype=torch.float64, device="cuda", requires_grad=True)

print(tensorGrad.requires_grad)

#...

with torch.no_grad():
    pass


True


## Tensoren erstellen

Es gibt auch noch eine Menge weiterer Funktionen, um Tensoren zu erstellen. Neben `torch.tensor()` gibt es verschiedene "Schablonen", mit denen man vorgerftigte Tensoren nutzen kann:
* `torch.empty(size)` - Tensor mit unitialisierten Daten
* `torch.ones(size)`
* `torch.ones_like(input: torch.Tensor)`
* `torch.zeros(size)`
* `torch.zeros_like(input: torch.Tensor)`
(verwendet man u.a. fürs Masking)

> Die "_like"-Funktionen benötigen einen `torch.Tensor` als Eingabe und nutzen die gleiche Form (`torch.Tensor.shape`), Dimension (`torch.Tensor.ndim`), Datentyp der Datenwerte (`torch.Tensor.dtype`) und Gerät (`torch.Tensor.device`).

In [ ]:
X = torch.tensor([[12.23, 3.2], [3.4, 5.6]])

a = torch.empty(3,3) # wie wird das initialisiert??
b = torch.ones(10,2)
c = torch.ones_like(input=z)
d = torch.zeros(100)
e = torch.zeros_like(input=X)
for tensor in [a, b, c, d, e]:
    print(tensor)

# was ist mit torch.empty_like, torch.full, torch.full_like, 

tensor([[8.4359e-25, 0.0000e+00, 1.3890e-05],
        [0.0000e+00, 1.1461e-02, 4.2273e-41],
        [1.3593e-43, 0.0000e+00, 9.4778e-30]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.])
tensor([[0., 0.],
        [0., 0.]])


Neben den obigen Funktionen bietet PyTorch auch noch folgende Muster: für 1-D und 2-D Tensoren!!!
* `torch.eye(n:int, m:int)` - 2-D Tensor mit Einsen auf der Diagonalen und Nullen überall sonst (Motivation des Bezeichners??)
* `torch.arange(start, end, steps:int)` - 1-D Tensor der Größe $\lceil \frac{end-start}{step}\rceil$ dessen Werte aus dem Intervall $[start, end)$ stamen mit einer gemeinsamen Differenzstufe beginnend bei `start` (Ende ist exklusiv)
* `torch.linspace()` - 1-D Tensor der Größe `steps` dessen Werte von Anfang bis Ende inklusiv gleichmäßig verteilt sind (linearly spaced)

> `torch.range` ist deprecated und sollte eher nicht verwendet werden.


In [ ]:
f = torch.eye(7,13)
g = torch.eye(6) #default: m=n (Einheitsmatrix!)
h = torch.arange(6) #default: start=0, steps=1; ein Vektor mit n Werten von 0 bis n-1
i = torch.arange(1,10) #default: steps=1; ein Vektor mit end-start Werten
j = torch.arange(1, 10, 0.7) # kann es hier nicht Rundungsfehler geben????, integer dtypes!!!!, oder epsilon verwenden!
k = torch.linspace(3, 10, steps=5)
l = torch.linspace(-10, 10, steps=5)
m = torch.linspace(start=-10, end=10, steps=5)
n = torch.linspace(start=-10, end=10, steps=2)

# es gibt auch noch torch.logspace

for tensor in [f, g, h, i, j, k, l, m, n]:
    print(tensor)

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]])
tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])
tensor([0, 1, 2, 3, 4, 5])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([1.0000, 1.7000, 2.4000, 3.1000, 3.8000, 4.5000, 5.2000, 5.9000, 6.6000,
        7.3000, 8.0000, 8.7000, 9.4000])
tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])
tensor([-10.,  -5.,   0.,   5.,  10.])
tensor([-10.,  -5.,   0.,   5.,  10.])
tensor([-10.,  10.])


### Bringen wir etwas mehr Zufall hinein
* `rand(size)` - zufällige Zahlen aus einer Gleichverteilung auf dem Intervall $[0,1)$, d.h. $x \sim \mathcal{U}(0,1)$
* `rand_like(input: torch.Tensor)` - $x \sim \mathcal{U}(0,1)$ auf dem Intervall $[0,1)$,
* `randint(low: int, high:int, size)` - $x \sim \mathcal{U}(low,high)$ auf dem Intervall $[low,high)$
* `randint_like(input: torch.Tensor, low:int, high:int)` - $x \sim \mathcal{U}(low,high)$ auf dem Intervall $[low,high)$
* `randn(size)`- zufällige Zahlen aus einer Normalverteilung mit Erwartungswert $\mu = 0$ und Varianz $\sigma^2 = 1$, d.h. $x \sim \mathcal{N}(0,1)$
(Standardnormalverteilung)
* `randn_like(input: torch.Tensor)` - $x \sim \mathcal{N}(0,1)$
* `normal()` - $x \sim \mathcal{N}(\mu,\sigma^2)$ (ist überladen!!!!!!!!!!)

(Anmerkung: Sowas gibt es auch in NumPy, oder durch die Python-Bibliothek `random`)

(Wie genau sind diese Funktionen implementiert??)

In [ ]:
o = torch.rand(4)
p = torch.rand(3,4) #ndim=2, shape=torch.Size([3,4])
q = torch.rand_like(X)
r = torch.randint(1, 10, (10,))
s = torch.randint_like(X, 1, 10)
t = torch.randn(4)
u = torch.randn(2,4) #ndim=2, shape=torch.Size([2,4])
v = torch.randn_like(X)
w = torch.normal(mean=torch.arange(1., 11.), std=torch.arange(1, 0, -0.1))
x = torch.normal(2, 3, size=(1, 4))

for tensor in [o, p, q, r, s, t, u, v, w, x]:
    print(tensor)


#Es gibt auch noch torch.bernoulli, torch.multinomial, torch.poisson, torch.randperm
# Sollte man grundsätzlich die Argumente bei Python-funktionen hinschreiben, oder nicht?
# Wie genau wird hier gesampelt??


tensor([0.7931, 0.3076, 0.0462, 0.2549])
tensor([[0.1223, 0.0152, 0.0996, 0.7202],
        [0.1012, 0.6805, 0.4431, 0.7649],
        [0.7047, 0.0071, 0.8302, 0.4833]])
tensor([[0.7547, 0.6261],
        [0.5027, 0.2383]])
tensor([1, 2, 3, 6, 3, 4, 9, 7, 2, 5])
tensor([[6., 9.],
        [4., 6.]])
tensor([ 0.2086,  0.2102,  0.8459, -0.4496])
tensor([[-1.5765,  0.7461,  1.1739,  0.5525],
        [-0.7298,  0.7917, -1.4118, -0.9586]])
tensor([[ 0.3828,  1.0361],
        [ 1.0880, -0.1976]])
tensor([ 2.3984,  1.3204,  2.2680,  3.8678,  4.1040,  6.2380,  7.1658,  7.7369,
         8.7722, 10.0545])
tensor([[ 2.6723,  1.4971, -0.9575,  5.2608]])


Für Numpy-Integration gibt es dann auch noch:
* `torch.from_numpy()`

In [60]:
import numpy as np

ar = np.array([1,2,3])

tensor1 = torch.from_numpy(ar)
print(tensor1)

tensor([1, 2, 3])


## Operationen auf Tensoren
> Wir schauen uns eigentlich nur die Methoden der Klasse `torch.Tensor` an und allgemeine Operationen auf Tensoren.

Seien die Tensoren $T, S \in \mathbb{R}^{k_1 \times k_2 \times \ldots \times k_i}$ und $c \in \mathbb{R}$. Ähnlich wie bei Matrixoperationen können wir auch hier die grundlegenden arithmetischen Operationen auf die Tensoren anwenden (sofern die Elemente eines Tensors Elemente einer algebraischen Struktur sind), u.a. 
- Skalarmultiplikation: $c \cdot T$ (in PyTorch: `c * T`)
- transponieren: $T^T$ (in PyTorch: `T.T`) (existiert nicht für 1D-Tensoren, muss ich nochmal durchdenken für höherdimensionale Tensoren)
(scheint ein Tensor der Größe $k_1 \times k_2 \times \ldots \times k_i$ zu einem Tensor der Größe $k_i \times k_{i-1} \times \ldots \times k_1$ zu machen)
(was genau macht transponieren eigentlich????)


Sofern die Tensoren gleich groß sind: (und `torch.dtype` und `torch.device` gleich sind)
- Tensoraddition: $T + S$ (in PyTorch: `T + S`, `__add__`) (assoziativ, kommutativ, distributiv mit dem Hadamard-Produkt)
- inverses Element der Tensoraddition (also Subtraktion): $T - S$ (in PyTorch: `T - S`, `__sub__`) (i.d.R. linksassoziativ)
- elementweise Tensormultiplikation (sog. Hadamard-Produkt): $T \circ S$ (in PyTorch: `T * S`, `__mul__`) (assoziativ, distributiv mit der Tensoraddition) (ist kommutativ in PyTorch)
(Es gibt viele mögliche Varianten, eine Tensormuliplikation zu definieren. Hier nutzen wir das Hadamard-Produkt übertragen auf Tensoren. Das ist keine Multiplikation im algebraischem Sinn!)
- inverses Element des Hadamard-Produktes: $T / S$ (in PyTorch: `T / S`, `__truediv__`) (i.d.R. linksassoziativ) (liefert inf bei Teilung durch 0!!; castet automatisch zu float32)

> Wir überladen hier bereits bekannte binäre Operationen aus Python.


@ -Operation!, `__matmul__` (min. 1D, nimmt keine Zahlen an!!!; Tensoren müssen passende Größen haben!)
(Matrixmultiplikation; spezielle Implementation; erlaubt kein dyadisches Produkt; strukturelle Informationen bei 1D-Tensoren werden ignoriert, d.h. hier existiert kein Zeilen- oder Spaltenvektor)
(bei 3D-Tensoren funktioniert das auch -> das muss ich noch mal überdenken)
(Spezialfälle der Matrixmultiplikation werden quasi verallgemeinert!!!!!)
(muss ich noch für höhere Dimensionen durchdenken, z.B. 3D-Tensor mal 3D-Tensor; oder Vektor mal 3D-Tensor, Vektor mal 4D-Tensor, etc.)


T + Skalar
T - Skalar
T / Skalar
T mod Skalar


- Modulo-Operation: $T \mod S$ (in PyTorch: `T % S`, `__mod__`) (i.d.R. linksassoziativ) (liefert `ZeroDivisionError`, wenn `S == 0`) (in der linearen Algebra definiert man glaube ich nicht die $mod$-Operation auf Tensoren)

> Wir überladen hier bereits bekannte binäre Operationen aus Python.




Präzedenz in PyTorch??


torch.multiply
torch.mul
torch.add
torch.matmul
torch.mm


(hier hätte ich gerne mehr theoretisches Wissen bzw. Wissen darüber, wie Tensoren mathematisch verstanden werden!)



ich müsste mir nochmal gesonert 3D-Tensoren, 4D-Tensoren, 5D-Tensoren, usw. anschauen!

bei Matrizen gebe ich ja durch die Array-Definition die strukturellen Informationen mit, bei Vektoren nicht

Werden die 1D-Tensoren nun als Spaltenvektoren verstanden???



in-place operations: indicated by _, e.g. add_






flatten() -> ist quasi Vektorisierung, d.h. man nutzt die Isomorphie von Tensorräumen zu $\mathbb{R}^n$

bereits bekannt: size(), type(), to(), numpy()


 
item() (funktioniert nur für einelementige Tensoren!)



Indexing: similar to python!!!!




Slicing




Joining




Mutating


cat(), reshape(), stack(), squeeze(), unsqueeze(), transpose(), permute()


mathematische Operationen: abs(), mul(), add(), matmul(), pow(), sum(), mean()



einsum()??

In [107]:
import torch

S = torch.tensor([1,2])
print(T)
T = torch.tensor([[[5,6,4, 2], [7,8,1,7]], [[7,6,3,3], [7,8,1,2]], [[7,6,3,3], [7,8,6,5]]])
R = torch.tensor([3,2,4])
U = torch.ones(2,3,4,5,6)
print(T)

W = T.T
print(W)


tensor([[[5, 6, 4, 2],
         [7, 8, 1, 7]],

        [[7, 6, 3, 3],
         [7, 8, 1, 2]],

        [[7, 6, 3, 3],
         [7, 8, 6, 5]]])
tensor([[[5, 6, 4, 2],
         [7, 8, 1, 7]],

        [[7, 6, 3, 3],
         [7, 8, 1, 2]],

        [[7, 6, 3, 3],
         [7, 8, 6, 5]]])
tensor([[[5, 7, 7],
         [7, 7, 7]],

        [[6, 6, 6],
         [8, 8, 8]],

        [[4, 3, 3],
         [1, 1, 6]],

        [[2, 3, 3],
         [7, 2, 5]]])


# GPGU with PyTorch
- torch.cuda
- torch.cuda.is_avalaible()
- torch.cuda.device_count()
- torch.Tensor.to()
- torch.Tensor.cpu()
- torch.accelerator
- torch.accelerator.current_accelerator
- torch.accelerator.type
- torch.accelerator.is_available()